#!/usr/bin/env python3
"""
Gallery builder for Shiv Printer House.

WORKFLOW
    1. Drop photos into  assets/images/gallery/originals/
    2. git add / commit / push
    3. The GitHub Action runs this script, which:
         - resizes each photo to 400 / 800 / 1600 px wide WebP
         - writes them to assets/images/gallery/
         - regenerates the markup inside gallery/index.html
       and commits the result. Cloudflare Pages then deploys.

RUN IT LOCALLY (optional, same result):
    python3 tools/build_gallery.py

CAPTIONS AND ORDER
    Optional file: assets/images/gallery/captions.json

        {
          "shopfront.jpg": {
            "caption": "Our shop on Gondal Road",
            "alt": "Shiv Printer House shopfront seen from Gondal Road",
            "group": "Our shop",
            "order": 1
          }
        }

    Anything omitted falls back to a title-cased version of the filename.
    Always write a real `alt` for photos that carry information — it is what
    screen-reader users and search engines read.

NOTE ON THE BUILD-STEP RULE
    The original brief forbids build pipelines. This script deliberately does
    not violate the spirit of that: it is an *authoring* tool whose output is
    committed. The deployed site remains plain static HTML with no runtime
    dependencies, and stays fully functional if this script is never run again.
"""
import json
import os
import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is required:  pip install Pillow")

ROOT = Path(__file__).resolve().parent.parent
ORIGINALS = ROOT / "assets/images/gallery/originals"
OUT = ROOT / "assets/images/gallery"
PAGE = ROOT / "gallery/index.html"
HOME = ROOT / "index.html"
CAPTIONS = OUT / "captions.json"

WIDTHS = [400, 800, 1600]
QUALITY = 80
SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".bmp"}

def markers(tag):
    return ("<!-- %s:START — generated by tools/build_gallery.py. Do not edit by hand. -->" % tag,
            "<!-- %s:END -->" % tag)

# Groups render in this order; anything else is appended alphabetically.
GROUP_ORDER = [
    "Our shop", "Workshop & repairs", "Spare parts & stock",
    "Printers we supply", "Our team", "Photos",
]


def esc(text):
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def load_captions():
    if not CAPTIONS.exists():
        return {}
    try:
        return json.loads(CAPTIONS.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        sys.exit("captions.json is not valid JSON: %s" % e)


def nice_name(stem):
    return stem.replace("-", " ").replace("_", " ").strip().capitalize()


def derive(src, meta):
    """Generate WebP derivatives. Returns (widths_written, largest_path, w, h)."""
    stem = src.stem.lower().replace(" ", "-")
    with Image.open(src) as im:
        im = ImageOps.exif_transpose(im)          # honour phone rotation
        im = im.convert("RGB")
        ow, oh = im.size
        written = []
        for w in WIDTHS:
            if w > ow and written:
                break                              # never upscale beyond the original
            target_w = min(w, ow)
            target_h = max(1, round(oh * target_w / ow))
            out = OUT / ("%s-%d.webp" % (stem, w))
            # Skip work if the derivative is already newer than the original.
            if out.exists() and out.stat().st_mtime >= src.stat().st_mtime:
                written.append((w, out, target_w, target_h))
                continue
            im.resize((target_w, target_h), Image.LANCZOS).save(
                out, "WEBP", quality=QUALITY, method=6)
            written.append((w, out, target_w, target_h))
    return written, ow, oh


def build():
    if not ORIGINALS.exists():
        ORIGINALS.mkdir(parents=True, exist_ok=True)
        print("created %s — drop photos in there" % ORIGINALS.relative_to(ROOT))

    captions = load_captions()
    photos = sorted(p for p in ORIGINALS.iterdir()
                    if p.is_file() and p.suffix.lower() in SUFFIXES)

    items = []
    for src in photos:
        meta = captions.get(src.name, {})
        written, ow, oh = derive(src, meta)
        if not written:
            continue
        largest = written[-1]
        items.append({
            "stem": src.stem.lower().replace(" ", "-"),
            "widths": written,
            "full": largest[1].name,
            "w": largest[2], "h": largest[3],
            "alt": meta.get("alt") or meta.get("caption") or nice_name(src.stem),
            "caption": meta.get("caption", ""),
            "group": meta.get("group", "Photos"),
            "order": meta.get("order", 9999),
        })
        print("  %-34s -> %s" % (src.name, ", ".join(str(w[0]) for w in written)))

    items.sort(key=lambda i: (i["order"], i["stem"]))

    groups = {}
    for it in items:
        groups.setdefault(it["group"], []).append(it)

    ordered = [g for g in GROUP_ORDER if g in groups]
    ordered += sorted(g for g in groups if g not in GROUP_ORDER)

    inject(PAGE, render(ordered, groups, len(items)), "GALLERY")
    inject(HOME, render_home(items), "HOMEGALLERY")
    print("\n%d photo(s) in %d group(s) -> %s + home teaser"
          % (len(items), len(ordered), PAGE.relative_to(ROOT)))
    return len(items)


def render_home(items):
    """Teaser strip for the home page.

    Deliberately renders NOTHING when there are no photos. An empty
    'photos coming soon' band on the home page of a live business site looks
    unfinished, so the section simply does not exist until real photos do.
    """
    if not items:
        # No wrapping <section> is emitted, so the home page has no empty band.
        return ("  <!-- Home gallery teaser appears here automatically once photos exist\n"
                "       in assets/images/gallery/originals/. See docs/GALLERY.md. -->")

    picks = items[:5]
    # First photo is the large cell, the rest stack beside it.
    spans = ["col-4 row-2", "col-2", "col-2", "col-2", "col-2"]

    out = ['  <section>',
           '    <div class="container">',
           '      <div class="section-head" data-reveal>',
           '        <span class="eyebrow">Our shop</span>',
           '        <h2>Have a look inside</h2>',
           '        <p>The counter on Gondal Road, the repair bench, and the parts we keep on the shelf.</p>',
           '      </div>',
           '      <div class="bento" data-reveal>']
    for span, it in zip(spans, picks):
        mid = next((p for w, p, _tw, _th in it["widths"] if w == 800), it["widths"][-1][1])
        srcset = ", ".join("assets/images/gallery/%s %dw" % (p.name, tw)
                           for _, p, tw, _th in it["widths"])
        out.append('        <figure class="bento-media %s">' % span)
        out.append('          <img src="assets/images/gallery/%s"' % esc(mid.name))
        out.append('               srcset="%s"' % esc(srcset))
        out.append('               sizes="(min-width: 64em) 40vw, 92vw"')
        out.append('               alt="%s" width="%d" height="%d"'
                   % (esc(it["alt"]), it["w"], it["h"]))
        out.append('               loading="lazy" decoding="async">')
        if it["caption"]:
            out.append('          <figcaption>%s</figcaption>' % esc(it["caption"]))
        out.append('        </figure>')
    out.append('      </div>')
    out.append('      <p class="mt-5 mb-0"><a href="gallery/">See the full photo gallery &rarr;</a></p>')
    out.append('    </div>')
    out.append('  </section>')
    return "\n".join(out)


def render(ordered, groups, total):
    if total == 0:
        return EMPTY_STATE

    out = []
    for group in ordered:
        out.append('      <section class="gallery-group" data-reveal>')
        out.append("        <h2>%s</h2>" % esc(group))
        out.append('        <div class="gallery" data-gallery>')
        for it in groups[group]:
            srcset = ", ".join(
                "../assets/images/gallery/%s %dw" % (p.name, tw)
                for _, p, tw, _th in it["widths"])
            # 800px derivative is the default src; browsers pick from srcset.
            mid = next((p for w, p, _tw, _th in it["widths"] if w == 800),
                       it["widths"][-1][1])
            out.append('          <figure>')
            out.append('            <a href="../assets/images/gallery/%s">' % esc(it["full"]))
            out.append('              <img src="../assets/images/gallery/%s"' % esc(mid.name))
            out.append('                   srcset="%s"' % esc(srcset))
            out.append('                   sizes="(min-width: 64em) 22vw, (min-width: 40em) 45vw, 92vw"')
            out.append('                   alt="%s" width="%d" height="%d"'
                       % (esc(it["alt"]), it["w"], it["h"]))
            out.append('                   loading="lazy" decoding="async">')
            out.append('            </a>')
            if it["caption"]:
                out.append("            <figcaption>%s</figcaption>" % esc(it["caption"]))
            out.append("          </figure>")
        out.append("        </div>")
        out.append("      </section>")
    return "\n".join(out)


# Shown to real visitors when no photos have been added yet, so it must read as
# customer-facing copy, not as instructions to the site owner. The instructions
# live in the HTML comment below and in docs/GALLERY.md.
EMPTY_STATE = """      <!-- No photos found in assets/images/gallery/originals/ yet.
           Add photos there and push; this block is replaced automatically.
           See docs/GALLERY.md. -->
      <div class="note" data-reveal>
        <h2 class="t-lg">Photos coming soon</h2>
        <p>We are putting together photos of the shop, the workshop bench and the
          parts we keep in stock. In the meantime you are very welcome to visit us
          on Gondal Road, or send us a WhatsApp message and we will send you a
          photo of any part or printer you are asking about.</p>
        <div class="btn-group mb-0">
          <a class="btn" href="../contact/">Visit or contact us</a>
          <a class="btn btn-outline" href="https://wa.me/919979468675" rel="noopener" target="_blank">Ask on WhatsApp</a>
        </div>
      </div>"""


def inject(path, html, tag):
    start, end = markers(tag)
    if not path.exists():
        sys.exit("%s is missing — cannot inject %s" % (path, tag))
    page = path.read_text(encoding="utf-8")
    if start not in page or end not in page:
        sys.exit("%s markers not found in %s" % (tag, path))
    head, rest = page.split(start, 1)
    _, tail = rest.split(end, 1)
    path.write_text(head + start + "\n" + html + "\n" + end + tail, encoding="utf-8")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    print("building gallery...")
    build()
